#pragma once

#include <string>
#include <vector>

#include <mi/neuraylib/ineuray.h>
#include <mi/neuraylib/itransaction.h>
#include <mi/neuraylib/imdl_backend.h>
#include <mi/neuraylib/imdl_execution_context.h>

namespace mdl_sky
{

struct MdlSkyResult
{
    // PTX generated by the MDL CUDA backend.
    std::string ptx;

    // Name of the generated callable function.
    std::string callable_name;

    // CUDA prototype of the generated callable.
    std::string callable_prototype;
};

// Compile ::base::perez_sun_and_sky() as an MDL environment function.
MdlSkyResult compile_perez_sun_and_sky(
    mi::neuraylib::INeuray* neuray,
    mi::neuraylib::ITransaction* transaction,
    mi::neuraylib::IMdl_execution_context* context);
} // namespace mdl_sky